ALTER TYPE "EntityType" ADD VALUE IF NOT EXISTS 'TUTOR_SESSION';
ALTER TYPE "EntityType" ADD VALUE IF NOT EXISTS 'TUTOR_TURN';
ALTER TYPE "EntityType" ADD VALUE IF NOT EXISTS 'LEARNING_SIGNAL';

ALTER TYPE "AIJobType" ADD VALUE IF NOT EXISTS 'TUTOR_TURN';
